apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: clustersecretstore-opin-dev
spec:
  provider:
    aws:
      service: SecretsManager
      region: ca-central-1
      auth:
        jwt:
          serviceAccountRef:
            name: secretmanager
            namespace: external-secrets