apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: my-external-secret
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: clustersecretstore-opin-dev
    kind: ClusterSecretStore
  target:
    name: my-kubernetes-secret # Nome do Secret no k8s
  data:
  - secretKey: password # chave do secret
    remoteRef:
      key: super-secret # Nome no Secret Manager